/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xoZ8wELRgcb
 */
import {Button} from "@/app/_components/ui/button"
import {CardTitle, CardDescription, CardHeader, CardContent, Card, CardFooter} from "@/app/_components/ui/card"
import {deleteMeme, fetchMemes} from "@/app/_actions/memes";
import {AddMemeForm} from "@/app/_components/AddMemeForm";
import {PlusIcon, TrashIcon} from "@heroicons/react/20/solid";

export const MemesPage = async () => {
    const memes = await fetchMemes()
    return (
        <div className="flex flex-col h-screen bg-white">
            <header className="flex items-center justify-between p-6 bg-green-500 shadow">
                <div className="flex items-center gap-2">
                    <h1 className="text-2xl font-bold text-white">memebox</h1>
                </div>
                <div className="flex items-center">
                    <a href={'/api/slack/install'}>
                        <Button className="ml-2 bg-white text-green-500">Update Slack Webhooks</Button></a>
                    <a href={'/api/auth/signout'}>
                        <Button className="ml-2 bg-white text-green-500">Sign Out</Button>
                    </a>
                </div>
            </header>
            <main className="flex-1 overflow-y-auto p-6">
                <div className="flex justify-between items-center mb-4">
                    <h2 className="text-xl font-semibold text-green-500">Memes</h2>
                    <AddMemeForm/>
                </div>
                <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-8">

                    {memes.map((meme) => (
                        <Card key={meme.id}
                              className="shadow-sm rounded-lg overflow-hidden transform hover:scale-105 transition-transform">
                            <CardHeader className="flex flex-col items-start p-4">
                                <CardTitle className="text-md font-bold">{meme.text || ''}</CardTitle>
                            </CardHeader>
                            <CardContent className="pb-2 px-4">
                                <p className="mb-2 text-xs">{meme.author || ''}</p>
                            </CardContent>
                            <CardFooter className="flex flex-col items-start p-4">
                                <CardTitle className="text-sm font-light">
                                    {ConvertJST(meme.created_at)}
                                    <form action={deleteMeme}>
                                        <input
                                            type="hidden"
                                            name="meme_id"
                                            id="meme_id"
                                            value={meme.id}
                                        />
                                        <button
                                            type="submit"
                                            className="absolute top-1 right-1 rounded-full text-red-400 p-1 shadow-sm hover:bg-red-400 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
                                        >
                                            <TrashIcon className="h-5 w-5" aria-hidden="true"/>
                                        </button>
                                    </form>
                                </CardTitle>
                            </CardFooter>
                        </Card>
                    ))}

                </div>
            </main>
        </div>
    )
}

const ConvertJST = (date: Date) => {
    return date.toLocaleString('ja-JP', {
        timeZone: 'Asia/Tokyo',
    });
}
